// F5 Categories — curated pool with tags and difficulty
// 284 categories across 10 tags. Tags prevent two from the same domain in one game.
// Difficulty: 1 = easy, 2 = medium, 3 = hard

const CATEGORIES = [
  // Nature
  { name: 'Animals', tag: 'nature', difficulty: 1 },
  { name: 'Birds', tag: 'nature', difficulty: 2 },
  { name: 'Flowers', tag: 'nature', difficulty: 2 },
  { name: 'Trees', tag: 'nature', difficulty: 2 },
  { name: 'Dog Breeds', tag: 'nature', difficulty: 2 },
  { name: 'Fish & Sea Life', tag: 'nature', difficulty: 2 },
  { name: 'Insects', tag: 'nature', difficulty: 2 },
  { name: 'Reptiles & Amphibians', tag: 'nature', difficulty: 3 },
  { name: 'Mammals', tag: 'nature', difficulty: 1 },
  { name: 'Mushrooms & Fungi', tag: 'nature', difficulty: 3 },
  { name: 'Sharks', tag: 'nature', difficulty: 3 },
  { name: 'Primates', tag: 'nature', difficulty: 3 },
  { name: 'Freshwater Fish', tag: 'nature', difficulty: 3 },
  { name: 'Farm Animals', tag: 'nature', difficulty: 1 },
  { name: 'Nocturnal Animals', tag: 'nature', difficulty: 3 },
  { name: 'Tropical Birds', tag: 'nature', difficulty: 3 },
  { name: 'Berries', tag: 'nature', difficulty: 2 },
  { name: 'Herbs (Botanical)', tag: 'nature', difficulty: 2 },
  { name: 'Snakes', tag: 'nature', difficulty: 2 },

  // Food & Drink
  { name: 'Fruits', tag: 'food', difficulty: 1 },
  { name: 'Vegetables', tag: 'food', difficulty: 1 },
  { name: 'Spices & Herbs', tag: 'food', difficulty: 2 },
  { name: 'Cheeses', tag: 'food', difficulty: 3 },
  { name: 'Cocktails & Drinks', tag: 'food', difficulty: 2 },
  { name: 'Desserts & Pastries', tag: 'food', difficulty: 2 },
  { name: 'Pasta Types', tag: 'food', difficulty: 3 },
  { name: 'Cuisines', tag: 'food', difficulty: 2 },
  { name: 'Nuts & Seeds', tag: 'food', difficulty: 3 },
  { name: 'Breads', tag: 'food', difficulty: 2 },
  { name: 'Candy & Chocolate', tag: 'food', difficulty: 2 },
  { name: 'Coffee Drinks', tag: 'food', difficulty: 2 },
  { name: 'Wines', tag: 'food', difficulty: 2 },
  { name: 'Beers & Breweries', tag: 'food', difficulty: 2 },
  { name: 'Teas', tag: 'food', difficulty: 2 },
  { name: 'Breakfast Foods', tag: 'food', difficulty: 1 },
  { name: 'Soups', tag: 'food', difficulty: 2 },
  { name: 'Sauces & Condiments', tag: 'food', difficulty: 2 },
  { name: 'Seafood', tag: 'food', difficulty: 2 },
  { name: 'Grains & Cereals', tag: 'food', difficulty: 2 },
  { name: 'Tropical Fruits', tag: 'food', difficulty: 2 },
  { name: 'Ice Cream Flavors', tag: 'food', difficulty: 1 },
  { name: 'Fast Food Chains', tag: 'food', difficulty: 1 },
  { name: 'Pizza Toppings', tag: 'food', difficulty: 1 },
  { name: 'Sandwiches', tag: 'food', difficulty: 2 },
  { name: 'Street Foods', tag: 'food', difficulty: 2 },
  { name: 'Salads', tag: 'food', difficulty: 2 },
  { name: 'Asian Noodle Dishes', tag: 'food', difficulty: 3 },

  // Geography
  { name: 'Countries', tag: 'geography', difficulty: 1 },
  { name: 'World Cities', tag: 'geography', difficulty: 1 },
  { name: 'U.S. States', tag: 'geography', difficulty: 1 },
  { name: 'Rivers', tag: 'geography', difficulty: 2 },
  { name: 'Mountains', tag: 'geography', difficulty: 2 },
  { name: 'Islands', tag: 'geography', difficulty: 2 },
  { name: 'Lakes', tag: 'geography', difficulty: 2 },
  { name: 'National Parks', tag: 'geography', difficulty: 2 },
  { name: 'Bodies of Water', tag: 'geography', difficulty: 2 },
  { name: 'Capitals', tag: 'geography', difficulty: 2 },
  { name: 'European Countries', tag: 'geography', difficulty: 1 },
  { name: 'African Countries', tag: 'geography', difficulty: 2 },
  { name: 'Asian Countries', tag: 'geography', difficulty: 2 },
  { name: 'Oceans & Seas', tag: 'geography', difficulty: 2 },
  { name: 'Continents & Regions', tag: 'geography', difficulty: 1 },
  { name: 'Waterfalls', tag: 'geography', difficulty: 3 },
  { name: 'Beaches', tag: 'geography', difficulty: 2 },
  { name: 'U.S. Cities', tag: 'geography', difficulty: 1 },
  { name: 'Caribbean Islands', tag: 'geography', difficulty: 2 },
  { name: 'South American Countries', tag: 'geography', difficulty: 2 },
  { name: 'Bays & Gulfs', tag: 'geography', difficulty: 3 },
  { name: 'World Landmarks', tag: 'geography', difficulty: 1 },
  { name: 'Bridges', tag: 'geography', difficulty: 2 },
  { name: 'Ski Resorts', tag: 'geography', difficulty: 2 },
  { name: 'Neighborhoods & Districts', tag: 'geography', difficulty: 3 },
  { name: 'Airports', tag: 'geography', difficulty: 2 },
  { name: 'Colleges & Universities', tag: 'geography', difficulty: 2 },
  { name: 'Famous Streets', tag: 'geography', difficulty: 2 },
  { name: 'Famous Buildings', tag: 'geography', difficulty: 2 },

  // Entertainment
  { name: 'Movies', tag: 'entertainment', difficulty: 1 },
  { name: 'TV Shows', tag: 'entertainment', difficulty: 1 },
  { name: 'Musical Artists', tag: 'entertainment', difficulty: 1 },
  { name: 'Songs', tag: 'entertainment', difficulty: 2 },
  { name: 'Broadway Musicals', tag: 'entertainment', difficulty: 3 },
  { name: 'Video Games', tag: 'entertainment', difficulty: 2 },
  { name: 'Board Games', tag: 'entertainment', difficulty: 3 },
  { name: 'Cartoon Characters', tag: 'entertainment', difficulty: 2 },
  { name: 'Actors & Actresses', tag: 'entertainment', difficulty: 1 },
  { name: 'Comedians', tag: 'entertainment', difficulty: 2 },
  { name: 'Animated Movies', tag: 'entertainment', difficulty: 2 },
  { name: 'Horror Movies', tag: 'entertainment', difficulty: 2 },
  { name: 'Sitcoms', tag: 'entertainment', difficulty: 2 },
  { name: 'Disney Characters', tag: 'entertainment', difficulty: 1 },
  { name: 'Superhero Characters', tag: 'entertainment', difficulty: 1 },
  { name: 'Movie Directors', tag: 'entertainment', difficulty: 2 },
  { name: 'Anime', tag: 'entertainment', difficulty: 2 },
  { name: 'Documentaries', tag: 'entertainment', difficulty: 2 },
  { name: 'Sci-Fi Movies', tag: 'entertainment', difficulty: 2 },
  { name: 'Action Movies', tag: 'entertainment', difficulty: 1 },
  { name: 'Romantic Comedies', tag: 'entertainment', difficulty: 2 },
  { name: 'Rock Bands', tag: 'entertainment', difficulty: 1 },
  { name: 'Hip-Hop Artists', tag: 'entertainment', difficulty: 2 },
  { name: 'Country Music Artists', tag: 'entertainment', difficulty: 2 },
  { name: 'Jazz Musicians', tag: 'entertainment', difficulty: 3 },
  { name: 'Music Genres', tag: 'entertainment', difficulty: 2 },
  { name: 'Music Festivals', tag: 'entertainment', difficulty: 2 },
  { name: 'Game Shows', tag: 'entertainment', difficulty: 2 },
  { name: 'Children\'s TV Shows', tag: 'entertainment', difficulty: 2 },
  { name: 'Movie Franchises', tag: 'entertainment', difficulty: 1 },
  { name: '90s TV Shows', tag: 'entertainment', difficulty: 2 },
  { name: '80s Music', tag: 'entertainment', difficulty: 2 },
  { name: '60s Movies', tag: 'entertainment', difficulty: 3 },
  { name: '70s Movies', tag: 'entertainment', difficulty: 3 },
  { name: '80s Movies', tag: 'entertainment', difficulty: 2 },
  { name: '90s Movies', tag: 'entertainment', difficulty: 2 },
  { name: '2000s Movies', tag: 'entertainment', difficulty: 2 },
  { name: '60s Songs', tag: 'entertainment', difficulty: 3 },
  { name: '70s Songs', tag: 'entertainment', difficulty: 3 },
  { name: '80s Songs', tag: 'entertainment', difficulty: 2 },
  { name: '90s Songs', tag: 'entertainment', difficulty: 2 },
  { name: '2000s Songs', tag: 'entertainment', difficulty: 2 },
  { name: '60s Musical Artists', tag: 'entertainment', difficulty: 3 },
  { name: '70s Musical Artists', tag: 'entertainment', difficulty: 3 },
  { name: '80s Musical Artists', tag: 'entertainment', difficulty: 2 },
  { name: '90s Musical Artists', tag: 'entertainment', difficulty: 2 },
  { name: '2000s Musical Artists', tag: 'entertainment', difficulty: 2 },

  // Arts & Letters
  { name: 'Authors', tag: 'arts', difficulty: 2 },
  { name: 'Painters', tag: 'arts', difficulty: 2 },
  { name: 'Novels', tag: 'arts', difficulty: 2 },
  { name: 'Poets', tag: 'arts', difficulty: 3 },
  { name: 'Composers', tag: 'arts', difficulty: 3 },
  { name: 'Philosophers', tag: 'arts', difficulty: 3 },
  { name: 'Dances', tag: 'arts', difficulty: 3 },
  { name: 'Sculptors', tag: 'arts', difficulty: 3 },
  { name: 'Playwrights', tag: 'arts', difficulty: 3 },
  { name: 'Art Movements', tag: 'arts', difficulty: 3 },
  { name: 'Shakespeare Plays', tag: 'arts', difficulty: 3 },
  { name: 'Architects', tag: 'arts', difficulty: 3 },
  { name: 'Photographers', tag: 'arts', difficulty: 3 },
  { name: 'Fashion Designers', tag: 'arts', difficulty: 2 },
  { name: 'Graphic Novels & Comics', tag: 'arts', difficulty: 2 },
  { name: 'Children\'s Books', tag: 'arts', difficulty: 2 },
  { name: 'Ballets', tag: 'arts', difficulty: 3 },
  { name: 'Museums', tag: 'arts', difficulty: 2 },
  { name: 'Fairy Tales & Fables', tag: 'arts', difficulty: 1 },
  { name: 'Fantasy Novels', tag: 'arts', difficulty: 2 },
  { name: 'Science Fiction Novels', tag: 'arts', difficulty: 2 },
  { name: 'Famous Paintings', tag: 'arts', difficulty: 2 },
  { name: 'Poetry Collections', tag: 'arts', difficulty: 3 },
  { name: 'Architecture Terminology', tag: 'arts', difficulty: 3 },
  { name: 'Design Terminology', tag: 'arts', difficulty: 3 },
  { name: 'Art Terminology', tag: 'arts', difficulty: 3 },
  { name: 'Music Terminology', tag: 'arts', difficulty: 3 },

  // History
  { name: 'U.S. Presidents', tag: 'history', difficulty: 2 },
  { name: 'Historical Figures', tag: 'history', difficulty: 2 },
  { name: 'Mythological Figures', tag: 'history', difficulty: 2 },
  { name: 'Ancient Civilizations', tag: 'history', difficulty: 2 },
  { name: 'World Leaders', tag: 'history', difficulty: 2 },
  { name: 'Royals & Monarchs', tag: 'history', difficulty: 2 },
  { name: 'Wars & Conflicts', tag: 'history', difficulty: 2 },
  { name: 'Civil Rights Leaders', tag: 'history', difficulty: 2 },
  { name: 'Women in History', tag: 'history', difficulty: 2 },
  { name: 'Ancient Greek Figures', tag: 'history', difficulty: 3 },

  // Science
  { name: 'Scientists', tag: 'science', difficulty: 2 },
  { name: 'Chemical Elements', tag: 'science', difficulty: 2 },
  { name: 'Inventions', tag: 'science', difficulty: 2 },
  { name: 'Diseases & Conditions', tag: 'science', difficulty: 3 },
  { name: 'Dinosaurs', tag: 'science', difficulty: 3 },
  { name: 'Body Parts & Organs', tag: 'science', difficulty: 1 },
  { name: 'Minerals & Rocks', tag: 'science', difficulty: 3 },
  { name: 'Planets & Moons', tag: 'science', difficulty: 2 },
  { name: 'Branches of Science', tag: 'science', difficulty: 2 },
  { name: 'Medical Specialties', tag: 'science', difficulty: 3 },
  { name: 'Constellations', tag: 'science', difficulty: 3 },
  { name: 'Vitamins & Minerals', tag: 'science', difficulty: 2 },
  { name: 'Bones of the Body', tag: 'science', difficulty: 3 },
  { name: 'Weather Phenomena', tag: 'science', difficulty: 2 },
  { name: 'Types of Energy', tag: 'science', difficulty: 2 },
  { name: 'Units of Measurement', tag: 'science', difficulty: 2 },
  { name: 'Psychology Terms', tag: 'science', difficulty: 2 },
  { name: 'Biomes & Ecosystems', tag: 'science', difficulty: 2 },
  { name: 'Computer Science Terms', tag: 'science', difficulty: 2 },

  // Sports
  { name: 'Olympic Sports', tag: 'sports', difficulty: 2 },
  { name: 'Team Sports', tag: 'sports', difficulty: 2 },
  { name: 'Athletes', tag: 'sports', difficulty: 2 },
  { name: 'Sports Teams', tag: 'sports', difficulty: 1 },
  { name: 'Stadiums & Arenas', tag: 'sports', difficulty: 2 },
  { name: 'Martial Arts', tag: 'sports', difficulty: 2 },
  { name: 'Sports Equipment', tag: 'sports', difficulty: 2 },
  { name: 'Famous Coaches', tag: 'sports', difficulty: 3 },
  { name: 'NBA Players', tag: 'sports', difficulty: 2 },
  { name: 'NFL Teams', tag: 'sports', difficulty: 1 },
  { name: 'Soccer Players', tag: 'sports', difficulty: 2 },
  { name: 'Tennis Players', tag: 'sports', difficulty: 2 },
  { name: 'MLB Teams', tag: 'sports', difficulty: 1 },
  { name: 'NHL Teams', tag: 'sports', difficulty: 2 },
  { name: 'Track & Field Events', tag: 'sports', difficulty: 2 },
  { name: 'Gymnastics Events', tag: 'sports', difficulty: 2 },
  { name: 'Winter Sports', tag: 'sports', difficulty: 2 },
  { name: 'Olympic Host Cities', tag: 'sports', difficulty: 2 },
  { name: 'Baseball Players', tag: 'sports', difficulty: 2 },
  { name: 'College Sports Teams', tag: 'sports', difficulty: 1 },

  // Things
  { name: 'Car Brands', tag: 'things', difficulty: 1 },
  { name: 'Clothing Items', tag: 'things', difficulty: 1 },
  { name: 'Musical Instruments', tag: 'things', difficulty: 2 },
  { name: 'Tools', tag: 'things', difficulty: 2 },
  { name: 'Currencies', tag: 'things', difficulty: 3 },
  { name: 'Languages', tag: 'things', difficulty: 2 },
  { name: 'Gemstones', tag: 'things', difficulty: 3 },
  { name: 'Professions', tag: 'things', difficulty: 1 },
  { name: 'Fabrics & Textiles', tag: 'things', difficulty: 3 },
  { name: 'Brands', tag: 'things', difficulty: 1 },
  { name: 'Furniture', tag: 'things', difficulty: 1 },
  { name: 'Colors', tag: 'things', difficulty: 1 },
  { name: 'Dances & Dance Styles', tag: 'things', difficulty: 2 },
  { name: 'Holidays & Celebrations', tag: 'things', difficulty: 1 },
  { name: 'Phobias', tag: 'things', difficulty: 3 },
  { name: 'Types of Shoes', tag: 'things', difficulty: 2 },
  { name: 'Toys', tag: 'things', difficulty: 2 },
  { name: 'Programming Languages', tag: 'things', difficulty: 2 },
  { name: 'Magazines', tag: 'things', difficulty: 2 },
  { name: 'Religions', tag: 'things', difficulty: 2 },
  { name: 'College Majors', tag: 'things', difficulty: 2 },
  { name: 'Kitchen Items', tag: 'things', difficulty: 1 },
  { name: 'Transportation', tag: 'things', difficulty: 1 },
  { name: 'Adhesives', tag: 'things', difficulty: 3 },
  { name: 'Yoga Poses', tag: 'things', difficulty: 3 },
  { name: 'Social Media Platforms', tag: 'things', difficulty: 1 },
  { name: 'Card Games', tag: 'things', difficulty: 2 },
  { name: 'Hairstyles', tag: 'things', difficulty: 2 },
  { name: 'Luxury Brands', tag: 'things', difficulty: 2 },
  { name: 'Architecture Styles', tag: 'things', difficulty: 3 },
  { name: 'Building Materials', tag: 'things', difficulty: 2 },
  { name: 'Garden Tools', tag: 'things', difficulty: 2 },
  { name: 'Office Supplies', tag: 'things', difficulty: 1 },
  { name: 'School Subjects', tag: 'things', difficulty: 1 },
  { name: 'Types of Hats', tag: 'things', difficulty: 2 },
  { name: 'Bags & Luggage', tag: 'things', difficulty: 2 },
  { name: 'Cleaning Products', tag: 'things', difficulty: 2 },
  { name: 'Military Ranks', tag: 'things', difficulty: 3 },
  { name: 'Legal Terms', tag: 'things', difficulty: 3 },
  { name: 'Hobbies', tag: 'things', difficulty: 1 },
  { name: 'Types of Stores', tag: 'things', difficulty: 1 },
  { name: 'Newspapers', tag: 'things', difficulty: 2 },
  { name: 'Car Models', tag: 'things', difficulty: 2 },
  { name: 'Types of Boats', tag: 'things', difficulty: 2 },
  { name: 'Cosmetics & Makeup', tag: 'things', difficulty: 2 },
  { name: 'Tech Companies', tag: 'things', difficulty: 2 },
  { name: 'Emojis', tag: 'things', difficulty: 2 },
  { name: 'Dog Commands', tag: 'things', difficulty: 3 },
  { name: 'Types of Knots', tag: 'things', difficulty: 3 },
  { name: 'Electronic Equipment', tag: 'things', difficulty: 2 },
  { name: 'Crayon Colors', tag: 'things', difficulty: 1 },
  { name: 'Occupations', tag: 'things', difficulty: 1 },

  // Humor & Creative
  { name: 'Things People Wear on Head or Face', tag: 'humor', difficulty: 1 },
  { name: 'Excuses to Skip Work or School', tag: 'humor', difficulty: 1 },
  { name: 'Exclamations', tag: 'humor', difficulty: 2 },
  { name: 'Things in a Junk Drawer', tag: 'humor', difficulty: 1 },
  { name: 'Things That Are Round', tag: 'humor', difficulty: 1 },
  { name: 'Things That Come in Pairs', tag: 'humor', difficulty: 1 },
  { name: 'Things at a Yard Sale', tag: 'humor', difficulty: 1 },
  { name: 'Things in a Hotel Room', tag: 'humor', difficulty: 1 },
  { name: 'Things That Bounce', tag: 'humor', difficulty: 2 },
  { name: 'Things in a Purse', tag: 'humor', difficulty: 1 },
  { name: 'Things That Are Sticky', tag: 'humor', difficulty: 2 },
  { name: 'Things That Melt', tag: 'humor', difficulty: 2 },
  { name: 'Things That Are Red', tag: 'humor', difficulty: 1 },
  { name: 'Things You\'d Bring Camping', tag: 'humor', difficulty: 1 },
  { name: 'Things in a Refrigerator', tag: 'humor', difficulty: 1 },
  { name: 'Things You\'d Find in a Backpack', tag: 'humor', difficulty: 1 },
  { name: 'Bad Gift Ideas', tag: 'humor', difficulty: 2 },
  { name: 'Things That Make Noise at Night', tag: 'humor', difficulty: 2 },
  { name: 'Things Grandparents Say', tag: 'humor', difficulty: 2 },
  { name: 'Things You\'d Find at the Beach', tag: 'humor', difficulty: 1 },
  { name: 'Weird Pizza Toppings', tag: 'humor', difficulty: 2 },
  { name: 'GenX Slang', tag: 'humor', difficulty: 2 },
  { name: 'Baby Boomer Slang', tag: 'humor', difficulty: 2 },
  { name: 'Millennial Slang', tag: 'humor', difficulty: 2 },
  { name: 'Gen Z Slang', tag: 'humor', difficulty: 2 },
  { name: 'Things That Are Blue', tag: 'humor', difficulty: 1 },
  { name: 'Things That Are Green', tag: 'humor', difficulty: 1 },
  { name: 'Things That Are Yellow', tag: 'humor', difficulty: 1 },
  { name: 'Things That Are White', tag: 'humor', difficulty: 1 },
  { name: 'Things That Are Black', tag: 'humor', difficulty: 1 },
  { name: 'Things at a Hardware Store', tag: 'humor', difficulty: 1 },
  { name: 'Things at a Grocery Store', tag: 'humor', difficulty: 1 },
  { name: 'Things at a Convenience Store', tag: 'humor', difficulty: 1 },

];

// Letters excluding Q, X, Z for standard mode
const STANDARD_LETTERS = 'ABCDEFGHIJKLMNOPRSTUVWY'.split('');
const EXPERT_LETTERS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');

export { CATEGORIES, STANDARD_LETTERS, EXPERT_LETTERS };
